import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  real,
  serial,
  text,
  timestamp,
  unique,
  uuid,
  vector,
} from 'drizzle-orm/pg-core';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';

export const notes = pgTable('notes', {
  id: serial('id').primaryKey(),
  body: text('body').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const insertNoteSchema = createInsertSchema(notes);
export const selectNoteSchema = createSelectSchema(notes);

export const homeruns = pgTable('homeruns', {
  id: serial('id').primaryKey(),
  season: integer('season').notNull(),
  playId: text('play_id').notNull().unique(),
  title: text('title').notNull(),
  exitVelocity: real('exit_velocity'),
  hitDistance: real('hit_distance'),
  launchAngle: real('launch_angle'),
  video: text('video'),
});

export const insertHomerunSchema = createInsertSchema(homeruns);
export const selectHomerunSchema = createSelectSchema(homeruns);

// Durable stats_* schema. Every table has a UUID surrogate PK; StatsAPI integer
// ids live as `mlb_id` unique columns and FKs reference the UUID PKs. `raw`
// holds the complete source object on every table.
export const statsTeams = pgTable('stats_teams', {
  id: uuid('id').primaryKey().defaultRandom(),
  mlbId: integer('mlb_id').notNull().unique(),
  name: text('name'),
  abbreviation: text('abbreviation'),
  teamName: text('team_name'),
  locationName: text('location_name'),
  leagueId: integer('league_id'),
  leagueName: text('league_name'),
  divisionId: integer('division_id'),
  divisionName: text('division_name'),
  venueMlbId: integer('venue_mlb_id'),
  firstYearOfPlay: text('first_year_of_play'),
  active: boolean('active'),
  raw: jsonb('raw'),
});

export const statsVenues = pgTable('stats_venues', {
  id: uuid('id').primaryKey().defaultRandom(),
  mlbId: integer('mlb_id').notNull().unique(),
  name: text('name'),
  city: text('city'),
  state: text('state'),
  stateAbbrev: text('state_abbrev'),
  country: text('country'),
  latitude: real('latitude'),
  longitude: real('longitude'),
  elevation: integer('elevation'),
  capacity: integer('capacity'),
  turfType: text('turf_type'),
  roofType: text('roof_type'),
  leftLine: integer('left_line'),
  center: integer('center'),
  rightLine: integer('right_line'),
  timezoneId: text('timezone_id'),
  timezoneOffset: integer('timezone_offset'),
  raw: jsonb('raw'),
});

export const statsPeople = pgTable('stats_people', {
  id: uuid('id').primaryKey().defaultRandom(),
  mlbId: integer('mlb_id').notNull().unique(),
  fullName: text('full_name'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  primaryNumber: text('primary_number'),
  birthDate: text('birth_date'),
  currentAge: integer('current_age'),
  birthCity: text('birth_city'),
  birthCountry: text('birth_country'),
  height: text('height'),
  weight: integer('weight'),
  active: boolean('active'),
  positionCode: text('position_code'),
  positionName: text('position_name'),
  positionType: text('position_type'),
  positionAbbrev: text('position_abbrev'),
  batSideCode: text('bat_side_code'),
  batSideDesc: text('bat_side_desc'),
  pitchHandCode: text('pitch_hand_code'),
  pitchHandDesc: text('pitch_hand_desc'),
  mlbDebutDate: text('mlb_debut_date'),
  raw: jsonb('raw'),
});

export const statsGames = pgTable('stats_games', {
  id: uuid('id').primaryKey().defaultRandom(),
  gamePk: integer('game_pk').notNull().unique(),
  gameGuid: text('game_guid'),
  season: integer('season'),
  gameType: text('game_type'),
  gameDate: text('game_date'),
  officialDate: text('official_date'),
  awayTeamId: uuid('away_team_id').references(() => statsTeams.id),
  homeTeamId: uuid('home_team_id').references(() => statsTeams.id),
  awayScore: integer('away_score'),
  homeScore: integer('home_score'),
  venueId: uuid('venue_id').references(() => statsVenues.id),
  statusAbstract: text('status_abstract'),
  statusDetailed: text('status_detailed'),
  statusCoded: text('status_coded'),
  dayNight: text('day_night'),
  doubleHeader: text('double_header'),
  gameNumber: integer('game_number'),
  seriesDescription: text('series_description'),
  seriesGameNumber: integer('series_game_number'),
  gamesInSeries: integer('games_in_series'),
  scheduledInnings: integer('scheduled_innings'),
  weatherCondition: text('weather_condition'),
  weatherTemp: text('weather_temp'),
  weatherWind: text('weather_wind'),
  winPitcherId: uuid('win_pitcher_id').references(() => statsPeople.id),
  lossPitcherId: uuid('loss_pitcher_id').references(() => statsPeople.id),
  savePitcherId: uuid('save_pitcher_id').references(() => statsPeople.id),
  attendance: integer('attendance'),
  raw: jsonb('raw'),
});

export const statsPlays = pgTable(
  'stats_plays',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    gameId: uuid('game_id').references(() => statsGames.id),
    atBatIndex: integer('at_bat_index'),
    resultType: text('result_type'),
    event: text('event'),
    eventType: text('event_type'),
    description: text('description'),
    rbi: integer('rbi'),
    isOut: boolean('is_out'),
    isScoringPlay: boolean('is_scoring_play'),
    halfInning: text('half_inning'),
    inning: integer('inning'),
    balls: integer('balls'),
    strikes: integer('strikes'),
    outs: integer('outs'),
    batterId: uuid('batter_id').references(() => statsPeople.id),
    pitcherId: uuid('pitcher_id').references(() => statsPeople.id),
    batSide: text('bat_side'),
    pitchHand: text('pitch_hand'),
    raw: jsonb('raw'),
  },
  (t) => [unique().on(t.gameId, t.atBatIndex)],
);

export const statsPitches = pgTable(
  'stats_pitches',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    gameId: uuid('game_id').references(() => statsGames.id),
    playIdFk: uuid('play_id_fk').references(() => statsPlays.id),
    atBatIndex: integer('at_bat_index'),
    pitchNumber: integer('pitch_number'),
    playId: text('play_id'),
    callCode: text('call_code'),
    callDescription: text('call_description'),
    description: text('description'),
    pitchTypeCode: text('pitch_type_code'),
    pitchTypeDesc: text('pitch_type_desc'),
    isInPlay: boolean('is_in_play'),
    isStrike: boolean('is_strike'),
    isBall: boolean('is_ball'),
    startSpeed: real('start_speed'),
    endSpeed: real('end_speed'),
    strikeZoneTop: real('strike_zone_top'),
    strikeZoneBottom: real('strike_zone_bottom'),
    zone: integer('zone'),
    typeConfidence: real('type_confidence'),
    plateTime: real('plate_time'),
    extension: real('extension'),
    px: real('px'),
    pz: real('pz'),
    pfxX: real('pfx_x'),
    pfxZ: real('pfx_z'),
    breakAngle: real('break_angle'),
    breakLength: real('break_length'),
    breakVertical: real('break_vertical'),
    breakVerticalInduced: real('break_vertical_induced'),
    breakHorizontal: real('break_horizontal'),
    spinRate: integer('spin_rate'),
    spinDirection: integer('spin_direction'),
    exitVelocity: real('exit_velocity'),
    launchAngle: real('launch_angle'),
    totalDistance: real('total_distance'),
    trajectory: text('trajectory'),
    hardness: text('hardness'),
    hitLocation: text('hit_location'),
    hitCoordX: real('hit_coord_x'),
    hitCoordY: real('hit_coord_y'),
    raw: jsonb('raw'),
  },
  (t) => [unique().on(t.gameId, t.atBatIndex, t.pitchNumber)],
);

export const statsRunners = pgTable('stats_runners', {
  id: uuid('id').primaryKey().defaultRandom(),
  gameId: uuid('game_id').references(() => statsGames.id),
  playIdFk: uuid('play_id_fk').references(() => statsPlays.id),
  runnerId: uuid('runner_id').references(() => statsPeople.id),
  originBase: text('origin_base'),
  startBase: text('start_base'),
  endBase: text('end_base'),
  outBase: text('out_base'),
  isOut: boolean('is_out'),
  isScoringEvent: boolean('is_scoring_event'),
  rbi: boolean('rbi'),
  earned: boolean('earned'),
  event: text('event'),
  eventType: text('event_type'),
  responsiblePitcherId: uuid('responsible_pitcher_id').references(() => statsPeople.id),
  raw: jsonb('raw'),
});

export const statsGameBatting = pgTable(
  'stats_game_batting',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    gameId: uuid('game_id').references(() => statsGames.id),
    teamId: uuid('team_id').references(() => statsTeams.id),
    personId: uuid('person_id').references(() => statsPeople.id),
    battingOrder: text('batting_order'),
    position: text('position'),
    atBats: integer('at_bats'),
    runs: integer('runs'),
    hits: integer('hits'),
    doubles: integer('doubles'),
    triples: integer('triples'),
    homeRuns: integer('home_runs'),
    rbi: integer('rbi'),
    baseOnBalls: integer('base_on_balls'),
    strikeOuts: integer('strike_outs'),
    stolenBases: integer('stolen_bases'),
    leftOnBase: integer('left_on_base'),
    totalBases: integer('total_bases'),
    plateAppearances: integer('plate_appearances'),
    hitByPitch: integer('hit_by_pitch'),
    sacFlies: integer('sac_flies'),
    sacBunts: integer('sac_bunts'),
    groundIntoDoublePlay: integer('ground_into_double_play'),
    raw: jsonb('raw'),
  },
  (t) => [unique().on(t.gameId, t.personId)],
);

export const statsGamePitching = pgTable(
  'stats_game_pitching',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    gameId: uuid('game_id').references(() => statsGames.id),
    teamId: uuid('team_id').references(() => statsTeams.id),
    personId: uuid('person_id').references(() => statsPeople.id),
    inningsPitched: text('innings_pitched'),
    hits: integer('hits'),
    runs: integer('runs'),
    earnedRuns: integer('earned_runs'),
    homeRuns: integer('home_runs'),
    baseOnBalls: integer('base_on_balls'),
    strikeOuts: integer('strike_outs'),
    battersFaced: integer('batters_faced'),
    pitchesThrown: integer('pitches_thrown'),
    balls: integer('balls'),
    strikes: integer('strikes'),
    wins: integer('wins'),
    losses: integer('losses'),
    saves: integer('saves'),
    holds: integer('holds'),
    blownSaves: integer('blown_saves'),
    hitBatsmen: integer('hit_batsmen'),
    wildPitches: integer('wild_pitches'),
    balks: integer('balks'),
    raw: jsonb('raw'),
  },
  (t) => [unique().on(t.gameId, t.personId)],
);

export const statsGameFielding = pgTable(
  'stats_game_fielding',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    gameId: uuid('game_id').references(() => statsGames.id),
    teamId: uuid('team_id').references(() => statsTeams.id),
    personId: uuid('person_id').references(() => statsPeople.id),
    putOuts: integer('put_outs'),
    assists: integer('assists'),
    errors: integer('errors'),
    chances: integer('chances'),
    passedBall: integer('passed_ball'),
    pickoffs: integer('pickoffs'),
    raw: jsonb('raw'),
  },
  (t) => [unique().on(t.gameId, t.personId)],
);

export const statsLinescore = pgTable(
  'stats_linescore',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    gameId: uuid('game_id').references(() => statsGames.id),
    inning: integer('inning'),
    ordinal: text('ordinal'),
    homeRuns: integer('home_runs'),
    homeHits: integer('home_hits'),
    homeErrors: integer('home_errors'),
    homeLob: integer('home_lob'),
    awayRuns: integer('away_runs'),
    awayHits: integer('away_hits'),
    awayErrors: integer('away_errors'),
    awayLob: integer('away_lob'),
    raw: jsonb('raw'),
  },
  (t) => [unique().on(t.gameId, t.inning)],
);

export const statsOfficials = pgTable('stats_officials', {
  id: uuid('id').primaryKey().defaultRandom(),
  gameId: uuid('game_id').references(() => statsGames.id),
  officialType: text('official_type'),
  personId: uuid('person_id').references(() => statsPeople.id),
  fullName: text('full_name'),
  raw: jsonb('raw'),
});

export const statsHomeruns = pgTable('stats_homeruns', {
  id: uuid('id').primaryKey().defaultRandom(),
  season: integer('season'),
  playId: text('play_id'),
  title: text('title'),
  exitVelocity: real('exit_velocity'),
  hitDistance: real('hit_distance'),
  launchAngle: real('launch_angle'),
  video: text('video'),
  raw: jsonb('raw'),
});

export const statsEmbeddings = pgTable(
  'stats_embeddings',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    sourceTable: text('source_table'),
    sourceId: uuid('source_id'),
    columnName: text('column_name'),
    content: text('content'),
    model: text('model'),
    embedding: vector('embedding', { dimensions: 1536 }),
  },
  (t) => [
    unique().on(t.sourceTable, t.sourceId, t.columnName),
    // HNSW over cosine distance: the durable RAG path orders by cosineDistance(embedding, q).
    index('stats_embeddings_hnsw').using('hnsw', t.embedding.op('vector_cosine_ops')),
  ],
);
